### PR TITLE
New: some UI

### PR DESCRIPTION
**Pull request by X-20A**
#73 
I wrote about the following UI, including the one I proposed in the issue

a. Clipboard copy function on results screen (a'. and simple notification function)
b.Keyboard shortcuts (for now, for the start of calculation)
c.One click on the text area for importing deck builder data will select all the data.

Each does not interfere with the other, so it is possible to incorporate them in parts.
What do you think?

https://github.com/KC3Kai/kancolle-replay/assets/155217226/f5616396-1a45-428f-8cee-ed2b462fa999

### CODE REVIEW

**Comment by X-20A** [comment]
I have edited some of the designs (see video)
I'd like to make sure the background doesn't scroll while the modal is displayed.
This is possible in ACSim, but it may be difficult if, for example, it depends on the structure of the component.
All these changes are completed in css.

https://github.com/KC3Kai/kancolle-replay/assets/155217226/295c75ac-84f6-47fe-87b6-0ce329775ec8

**Comment by fourinone41** [comment]
Thank you for these contributions. I have adapted the following based on your code:
- a. Clipboard copy function on results screen (a'. and simple notification function)
- c.One click on the text area for importing deck builder data will select all the data.
- overscroll-behavior

Question:
> retreat: 12.8%, S rate: 63.5%

I think it may be ambiguous without context of other stats (e.g. showing they sum to 100%), unclear if it means "X% retreat, AND Y% S-rank overall including retreats" (correct) or "X% retreat, THEN Y% S-rank only if you reach boss node" (wrong). Do you think it's still useful to include retreat rate in the copied text?

By the way, are you a JP speaker? I wonder would you be interested in translating other UI terms to JP? I was thinking to add i18n support, so let me know if you're interested.

**Comment by X-20A** [comment]
>I think it may be ambiguous without context of other stats (e.g. showing they sum to 100%), unclear if it means "X% retreat, AND Y% S-rank overall including retreats" (correct) or "X% retreat, THEN Y% S-rank only if you reach boss node" (wrong). Do you think it's still useful to include retreat rate in the copied text?

The copy button is on the "Avg Resource Per~" and away from the "Rank Per Battle".
I think it's hard to confuse the two.
The retreat rate is an important indicator for optimizing the composition and efficiency of laps, so I think it's better to include it.
Although confusion could be avoided if some kind of explanation is given to the text to be copied,
However, if the user has to edit the text manually, it may be a total waste of time.
I would prefer to be as concise as possible.

>By the way, are you a JP speaker? I wonder would you be interested in translating other UI terms to JP? I was thinking to add i18n support, so let me know if you're interested.

Yes, I am a native Japanese speaker.
I have not written directly about i18n, but, well, I can probably work something out, and it will be meaningful for Japanese users.
How about starting a new issue?

**Comment by X-20A** [comment]
What is the 'Special Attack Activation Rate'?

**Comment by X-20A** [comment]
Does "Shelling Range Tie Randomness Weights" mean that there is a bias in the order of attack when there are multiple ships with the same range?

**Comment by X-20A** [comment]
Does "Override Support Fleet Chance" mean the probability that the support fleet will not come?
And is the value fixed?

**Comment by fourinone41** [comment]
My suggestion is to include all possible outcomes summing to 100%:
`S rate: 63.5% (retreat: 12.8%, non-S: 23.7%)`
Do you think this is better?

> What is the 'Special Attack Activation Rate'?

These are the fixed values which the simulator uses to determine the chance of Special Attacks triggering. Since the actual formulas are not well understood, there is no automatic fleet-based calculation implemented, it uses only these fixed values.
If in the future I do implement automatic calculation, then these will work as "overrides", just like "Override Support Fleet Chance" below.

> Does "Shelling Range Tie Randomness Weights" mean that there is a bias in the order of attack when there are multiple ships with the same range?

Yes. For example, it is the same behaviour described here: https://cc-jabberwock.hatenablog.com/entry/2023/01/28/230903

> Does "Override Support Fleet Chance" mean the probability that the support fleet will not come?
And is the value fixed?

It means "the probability that the support fleet comes, which replaces the usual calculation". The purpose is to experiment with new 艦隊通信アンテナ effects, since we do not know the calculations yet. The values are fixed.

**Pull request closed without merging**
